### ISSUE TITLE
About the FEMNIST with 4-way evaluation

### ISSUE THREAD

**Issue by HiHippie** [yuetan031/fedproto#2]
Thank you for this excellent work.
Could you please release your hyper-parameter setup when conducting the 4-way FEMNIST experiment?
I work well for the 3/5-way FEMNIST evaluation.
However, I found the following bug when conducting the 4-way one.

Round 0, User 17:

FileNotFoundError: [Errno 2] No such file or directory: '../data/femnist\\data\\raw_data\\by_class\\6a\\train_6a\\train_6a_02002.png'

Best regards

**Comment by yuetan031** [comment]
Hi,
The reason for that is there isn't enough samples for partitioning (only 1919 samples available in 6a class). You may try smaller k or smaller number of clients or even different random seed here.
Thanks for pointing out this bug, I will figure it in later version.
